// Biblioteca de videos de técnica: un Short de YouTube por ejercicio, siempre en español
// (los clientes están en Argentina), de entrenadores y kinesiólogos hispanohablantes.
// Cada uno se eligió mirando sus fotogramas (workflow "Fotos de videos"): tiene que mostrar
// el ejercicio exacto con el equipo correcto y ser una demostración directa, sin charla larga.
// Solo se enlaza (se abre en YouTube): no se descarga ni se vuelve a subir nada, así el video
// sigue siendo de su autor, con su canal y su crédito. Si el coach pega su propio link en el
// ejercicio, manda el del coach.
// Cada lunes el workflow "Videos" revisa que sigan existiendo (scripts/verificar-videos.mjs).
//
// Clave: nombre del ejercicio como está en EX_DB (sin tildes ni mayúsculas, ver norm()).
// Valor: [id del Short, canal].

const V = {
  "Press de banca plano (barra)": ["t5IohlVI31I", "Collado Fitness"],
  "Press inclinado en Smith": ["2fGdO3aNW8U", "Paco Sierra Fit"],
  "Fondos en paralelas": ["1fR3Ss8OFug", "Arceo Fitness"],
  "Aperturas en polea baja": ["Qabb6ejh9Gg", "Pump Center"],
  "Jalón neutro": ["lZ-oUuV1Aj0", "Mauro Hernandez"],
  "Remo unilateral con mancuerna": ["VyJiyek7F3I", "Laura Rozo"],
  "Hiperextensiones lumbares": ["bLPebovecmg", "Zona del Entrenador"],
  "Pullover con mancuerna": ["Y2WPDYf4Zzw", "Your House Fitness"],
  "Rack pull": ["WbaoujV7-P4", "Pablohentrenador"],
  "Vuelos laterales en polea": ["V98wql8IfVA", "Valentínfitnesscoach"],
  "Jalón a la cara": ["ThpuOpbR9b4", "Myprotein España"],
  "Press militar sentado": ["5jZGLKrVUpA", "VekaHealthyLife"],
  "Curl martillo": ["WOxdd51XqVU", "Your House Fitness"],
  "Curl araña": ["GlzMRSOoJ_w", "Alejandro Gamez"],
  "Curl 21": ["GpGP1N4pvbM", "Motivacion Monstergym"],
  "Patada de tríceps": ["JJ_DuVCLpGc", "Rams · Preparación Física & Entrenamiento"],
  "Extensión de tríceps parado en polea": ["smLEQsRMnc8", "CosmicCoach"],
  "Sentadilla frontal": ["nOilmCM2TPI", "GymTravelerOrg"],
  "Extensión de cuádriceps a una pierna": ["kG83qbQ5l4I", "Samucfit"],
  "Cuadricera": ["iNvPzf15KKA", "Profe Sasso"],
  "Sentadilla sumo": ["TSrhPvAemzA", "Your House Fitness"],
  "Peso muerto piernas rígidas": ["JwXp2kjs974", "Fuerza Pura"],
  "Curl femoral con fitball": ["Chr-WhmKIaI", "Natyfitness"],
  "Abductores": ["HJLzMM_naPg", "Abraham Ysas"],
  "Patada de glúteo en cuadrupedia": ["FJPlxW8CZI0", "Juan José Garcia / Project180 / Running"],
  "Gemelos en prensa": ["_EkH6H7GNyY", "Antonio Vera"],
  "Encogimiento abdominal": ["BzYrN4o5X5o", "ClaudiaFitness"],
  "Encogimiento en polea": ["Rbv92fjUPsE", "Priscilla_bc"],
  "Bicicleta abdominal": ["K79CoGMh7P0", "Geras Gym"],
  "Bandera": ["bLCUS2XVIhU", "Hybrid Calisthenics en Español"],
  "Curl de muñeca": ["EpaLm7tCTyk", "DimarcoFitnessCenter"],
  "Curl Zottman": ["hnGBmyeXWaQ", "Good Way Fitness"],
  "Press de banca inclinado (barra)": ["5XRE9cnnfVw", "Emearenafit"],
  "Aperturas con mancuernas": ["u-DlxTyg2Ek", "Valeria Claros"],
  "Flexiones de brazos": ["e6gPqb93DnQ", "Gym Day"],
  "Flexiones diamante": ["bZJW_GR9jUk", "Pipe Arenas"],
  "Jalón en V": ["CRSaYsLR2qk", "Luna Boccia Morello"],
  "Remo en máquina": ["mNnr_j72_pE", "BenjaminTrainer"],
  "Jalón unilateral en estocada": ["L3isMvyckQU", "Luis Pérez PFisica"],
  "Remo con mancuerna en banco inclinado": ["xOyGZDjOoTE", "AleFit"],
  "Press militar con barra": ["jpi8pC95ubY", "Valentínfitnesscoach"],
  "Vuelos laterales en máquina": ["vthHF1LHn5o", "lorenzo aznar ramon"],
  "Encogimientos de hombros": ["QgokS_HikVo", "Alberto Hiciano IFBB PRO"],
  "Rotación externa en polea": ["BTb5gnkYk8g", "CORPO FIT"],
  "Curl predicador": ["uXaz4wPNaxs", "Zona del Entrenador"],
  "Curl bíceps en polea baja frontal": ["cr46GuiqIdI", "Mikel Hernández Recio"],
  "Curl con barra supino en polea": ["_cgSSelhgF8", "Priscilla_bc"],
  "Press cerrado": ["sm6evsqbONc", "Mario Vicent / ENTRENADOR ONLINE"],
  "Extensión de tríceps unilateral en polea": ["hip11n3QXzU", "TEAMCHORPA"],
  "Sentadilla en Smith": ["7cxG2c2j6es", "CosmicCoach"],
  "Zancadas": ["OOoMo14FPmM", "Alejandra Murcia"],
  "Sentadilla goblet": ["_k4IXw5bGmc", "Zona del Entrenador"],
  "Curl femoral acostado": ["nmqG-tIr0hc", "Priscilla_bc"],
  "Peso muerto convencional": ["rzpikhhtwwA", "Luis Serra"],
  "Empuje de cadera": ["zaSzxo6xleY", "Priscilla_bc"],
  "Abducción en polea": ["1lnTMSjC13Y", "Juanvahos023"],
  "Caminata lateral con banda": ["N88axM6v130", "AntoCar Wellness"],
  "Gemelos en Smith": ["Nqg_ECwg-bU", "Martin Zeballos"],
  "Encogimiento declinado": ["WNe8AHY3Hic", "Estutrainer"],
  "Giro ruso": ["Xvm7zSiFyak", "Dani Villar Iglesias"],
  "Puntas a la barra": ["Ks9xMElX5bs", "Arceo Fitness"],
  "Abdominales en V": ["Imw7PzoP2Vw", "Javier V Carrión"],
  "Curl de muñeca invertido": ["TjmowP_tm1U", "JMF-PersonalTrainer"],
  "Enrollador de muñeca": ["TYk4vZtFgjc", "Chuy Almada"],
  "Press de banca declinado": ["HVFEYGoBo1w", "Leo Romano preparador rugby"],
  "Aperturas inclinadas": ["CQx4FhzelMU", "GymTravelerOrg"],
  "Press de pecho en máquina": ["88kSaeQG21Y", "Priscilla_bc"],
  "Press de pecho en máquina inclinado": ["YS6DsKrY8T0", "Angelo Flores Arias"],
  "Jalón en estocada": ["L3isMvyckQU", "Luis Pérez PFisica"],
  "Remo en máquina unilateral": ["6iqRrfqe2s0", "TE ENTRENA HUGOTUENTRENADOR"],
  "Remo neutro abierto en polea baja": ["UdQRqzTcjOI", "Manuel Lobo"],
  "Remo invertido": ["NJWqM0gLLsk", "Ignacio Nocelli"],
  "Press Arnold": ["wpsaMyaEJk4", "GymTravelerOrg"],
  "Vuelos posteriores": ["7XlacU-6vX4", "Laura Pérez - Tu dietista y entrenadora vegana"],
  "Vuelo lateral en polea (énfasis estiramiento)": ["ZNSqWafVNwM", "Dra Corin Andrade"],
  "Curl con barra": ["B3Feq30xwpo", "Priscilla_bc"],
  "Curl en banco inclinado": ["r5kZ6XPAwZg", "Estutrainer"],
  "Curl Bayesian": ["XGGO0bUmttw", "matias coach"],
  "Press francés con barra": ["CAUWI4sNPKk", "Valentínfitnesscoach"],
  "Fondos entre bancos": ["hVwojhhQhj4", "Pipe Arenas"],
  "Fondos en máquina": ["TNlDOhn8icM", "Jorge González"],
  "Sentadilla hack": ["THmzH1H3yj8", "Oscarsfit"],
  "Sentadilla búlgara": ["t4-_udCqwqI", "Myprotein España"],
  "Sentadilla pendular": ["37LXKDPUbsU", "Diego Colungo"],
  "Curl femoral sentado": ["YXXNyNGCXgs", "Laura Rozo"],
  "Buenos días": ["Gb0jbzkA2TU", "tecnicaejercicios"],
  "Empuje de cadera en máquina": ["YekhXgSkk2o", "Verania Rdz Fitness"],
  "Aductores": ["vlViIgtkvh4", "Priscilla_bc"],
  "Hiperextensión para glúteo": ["aWom2k7z_II", "FitConNerea"],
  "Gemelos burro": ["GKXfmfyOThE", "ARTURO CAMPOS COACH"],
  "Elevación de piernas": ["Be3jdafVWAk", "Agostina Guenzani"],
  "Escaladores": ["Fb79R7IUwYE", "Luis Serra"],
  "Plancha hueca": ["ia3a0Mbt-9A", "HIGH SPORTS PERFORMANCE"],
  "Crunch en banco": ["z5lVHx8FqPU", "defelicefitness"],
  "Curl invertido con barra": ["hplJJt9lQb8", "MATI FERNANDEZ COACH FITNESS"],
  "Colgarse de la barra": ["PL_5UGrcEc8", "Profe Diego"],
  "Press plano con mancuernas": ["O_NGJ2DcBAs", "Alex Valdez"],
  "Aperturas en máquina": ["kGVhRoYlb50", "BenjaminTrainer"],
  "Peck deck": ["Y4jzm2c3szA", "Coach Terry"],
  "Dominadas": ["jQROLPOflYg", "Pipe Arenas"],
  "Jalón con brazos rectos en polea": ["fVxZ6tIlXnk", "Level up fitnes"],
  "Remo en polea baja": ["iyOM6y5ADAQ", "Gym Topz"],
  "Remo en polea baja unilateral": ["T_EChQwqWdc", "FocusAtlethic"],
  "Dominadas asistidas": ["7ygCGEEpORk", "Dra Corin Andrade"],
  "Press de hombros con mancuernas": ["sWJoAATDlGM", "Laura Rozo"],
  "Posterior en máquina": ["6zDLYgPON3Q", "Priscilla_bc"],
  "Remo al mentón": ["VOAwxHxdLg0", "Valentínfitnesscoach"],
  "Curl con barra Z": ["LJsKigemdwk", "Antony8ap"],
  "Curl en polea": ["_cgSSelhgF8", "Priscilla_bc"],
  "Curl predicador en polea": ["NfPUoyn-20w", "FITNESS CON CEREBRO"],
  "Press francés con mancuernas": ["vEimgdnKHVw", "Michel Cuevas entrenador"],
  "Extensión sobre la cabeza": ["LvYIcAEy1Ws", "NFIT"],
  "Extensión de tríceps en máquina": ["6iKEO0xT5jc", "Zona del Entrenador"],
  "Prensa 45": ["NYa0tZCW4fk", "Coach Honorio Landa"],
  "Sentadilla con mancuerna al pecho": ["2KbVt1Gl0VM", "Joseaguirrefitness"],
  "Sentadilla con cinturón": ["v2uoheVQRi8", "Virtual Trainer - Jhonbafit"],
  "Curl femoral de pie": ["CPCYh7OY4AU", "walther Alcivar"],
  "Curl nórdico": ["QZdcn8POwbw", "Miguel Leon Trainer"],
  "Puente de glúteo": ["UACIKae85Sk", "Paola"],
  "Peso muerto sumo": ["eBu8SPUTEmk", "Priscilla_bc"],
  "Step-up para glúteo": ["CsA5BJBcvxU", "Perla Fitness tips"],
  "Gemelos a una pierna": ["wleVRP2dPv4", "claracortf"],
  "Elevación de piernas colgado": ["vsG3ufxXtUo", "Clinica de Fisioterapia Raúl Ramos"],
  "Oblicuos": ["x7Ob3Z42TxI", "Alberto Celda"],
  "Bicho muerto": ["vn72PVWnu14", "Martinhm"],
  "Pallof press": ["WCKzrxJPEqo", "Dra. Isabel Junio"],
  "Caminata del granjero": ["_HF4zc5t6A8", "Matías Soto"],
  "Pinza con disco": ["SM_1mmEqPzY", "Vital - Centro de entrenamiento"],
  "Press inclinado con mancuernas": ["LDEHmb9DpO8", "GymTravelerOrg"],
  "Cruce de poleas": ["QEW6RO0O-ak", "AmCoder Fit"],
  "Cruce de poleas descendente": ["5k_BHoOsrKU", "Daniel Solá - Entrenador Online"],
  "Dominadas neutras": ["eSHaWsrTg9Y", "CLAUDIA ARTEAGA FIT"],
  "Remo con barra": ["RgrfbOugq6s", "Pipe Arenas"],
  "Remo en barra T": ["O4cgV2PKamE", "Juana Lujan"],
  "Remo alto en polea": ["jGPlDJ5sxLI", "Vigor Fitness Uy"],
  "Jalón supino": ["YXbO6g7Tnfg", "Alberto Hiciano IFBB PRO"],
  "Press de hombros en Smith": ["6JjefpHUsCg", "WALTERFITPRO"],
  "Posterior en polea": ["xwSS42EwMGc", "Nación 52"],
  "Press landmine": ["UKB4Ere3zVE", "Cris Provecho"],
  "Curl con mancuernas": ["WrpQYs_n_Pw", "Fisio Fitness App"],
  "Curl en polea detrás del cuerpo": ["J_-lkeKmHB8", "Martinhm"],
  "Curl martillo en polea": ["Oy6M5aQPsko", "GymTravelerOrg"],
  "Extensión en polea": ["KP2p7IZ_K30", "Alberto Hiciano IFBB PRO"],
  "Katana en polea": ["ImsJtwR1FjU", "Martinhm"],
  "Press JM": ["vrvar3KLhN4", "Coach Barus"],
  "Prensa horizontal": ["cMK4Q-aQJxY", "Priscilla_bc"],
  "Subida al cajón": ["CsA5BJBcvxU", "Perla Fitness tips"],
  "Zancadas caminando": ["Q--hFojmGZE", "Francisco"],
  "Peso muerto rumano": ["BSLuRD7fZwc", "Squat University Español"],
  "Camilla de isquios": ["nmqG-tIr0hc", "Priscilla_bc"],
  "Patada de glúteo en polea": ["gufd8I2QCjI", "Annia Wilkomirsky  Personal Trainer  Chilena"],
  "Aductores en máquina": ["vlViIgtkvh4", "Priscilla_bc"],
  "Gemelos de pie": ["OCpCLsrYfUU", "Dani García Martínez"],
  "Gemelos en máquina": ["goHLe1fninw", "IvoFitness"],
  "Plancha": ["ysX1CpHKGCo", "Dra. Isabel Junio"],
  "Plancha lateral": ["GaugOQIlUPs", "Valentínfitnesscoach"],
  "Leñador en polea": ["qmKUpSRijgc", "Estutrainer"],
  "Elevación de rodillas en paralelas": ["2kigjHj99Lk", "Minimuri Endurance Training Team"],
  "Curl de antebrazo en polea": ["wwFCRAvZPH0", "Frank Guerson"],
  "Pinza de mano": ["7nGlaCcItAY", "CrushBromx"],
  "Press plano en Smith": ["JBzfj0oVDco", "LuisHerra"],
  "Vuelos en polea": ["5oX3KUSiqy4", "Myprotein España"],
  "Press declinado con mancuernas": ["MYJfiyYi2q0", "GymTravelerOrg"],
  "Jalón al pecho": ["udUQ99c3oRE", "Karen Zárate"],
  "Remo Pendlay": ["wAYL4RiqFDs", "Luis Serra"],
  "Jalón con brazos rectos y mancuerna": ["Y2WPDYf4Zzw", "Your House Fitness"],
  "Pullover en polea": ["kXLRGQLISG4", "Priscilla_bc"],
  "Vuelos laterales con mancuernas": ["dd9xo-_ahCg", "Priscilla_bc"],
  "Elevaciones frontales": ["PTRTYb1ZZv0", "Your House Fitness"],
  "Elevación Y en banco inclinado": ["itvKYjCRZK0", "Be The Strongest"],
  "Curl alternado": ["5f1VbxBtFpQ", "Luis García"],
  "Curl concentrado": ["kcakHyAiyZo", "FRANK SERAPIÓN"],
  "Curl en máquina": ["C0xuU9_wlkg", "JMF-PersonalTrainer"],
  "Extensión con soga": ["c8Ewj6sLuSs", "Priscilla_bc"],
  "Katana en Smith": ["Np-eDvgjnL8", "Mauro Fialho"],
  "Sentadilla libre": ["4Gzv-EjUclo", "Priscilla_bc"],
  "Extensión de cuádriceps": ["xj5u9RvlkmA", "BenjaminTrainer"],
  "Sentadilla sissy": ["qKjPofztR2M", "Sportfitness"],
  "Zancada inversa": ["umuACQ9Ks5c", "Priscilla_bc"],
  "Peso muerto rumano con mancuernas": ["pQQrNsuCSug", "Pablo Torres"],
  "Peso muerto rumano a una pierna": ["7ulHtv30lxM", "Victor Romero Coach"],
  "Patada de glúteo en máquina": ["HlrLyKsrV78", "Valentínfitnesscoach"],
  "Empuje de cadera a una pierna": ["I9rpc45zG00", "Iona Fit"],
  "Gemelos sentado": ["jpyhqVpnmVE", "Alberto Hiciano IFBB PRO"],
  "Elevación de tibial": ["-pGwwrUWL4w", "Professional Performance Training - Proper"],
  "Rueda abdominal": ["ODRGMj5qEbY", "Arceo Fitness"],
  "Encogimiento invertido": ["009ABmp398k", "ejercicios․com"],
  "Encogimiento en máquina": ["l98-SYsMO0s", "Alex Moreno Trainer"],
  "Plancha con toque de hombros": ["wWn0_iElP0o", "Sthefanía Henao"],
  "Curl de muñeca con mancuerna": ["JrCRzibnz4Y", "DimarcoFitnessCenter"],
};

// Otros nombres con los que aparece el mismo ejercicio.
const ALIAS = {
  "Prensa 45°": "Prensa 45",
  "Remo T": "Remo en barra T",
  "Elevaciones laterales": "Vuelos laterales con mancuernas",
  "Vuelos laterales sentado": "Vuelos laterales con mancuernas",
  "Jalón prono": "Jalón al pecho",
  "Sentadilla": "Sentadilla libre",
  "Press de banca": "Press de banca plano (barra)",
  "Hip thrust": "Empuje de cadera",
  "Face pull": "Jalón a la cara",
  "Dead bug": "Bicho muerto",
  "Paseo del granjero": "Caminata del granjero",
  "Plancha abdominal": "Plancha",
  "Plancha frontal": "Plancha",
  "Curl alternado con mancuernas": "Curl alternado",
  "Pullover": "Pullover en polea",
  "Remo gironda": "Remo en polea baja",
  "Polea al pecho": "Jalón al pecho",
  "Estocadas": "Zancadas",
  "Sillón de cuádriceps": "Extensión de cuádriceps",
  "Crunch abdominal": "Encogimiento abdominal",
  "Crunch en polea": "Encogimiento en polea",
  "Crunch invertido": "Encogimiento invertido",
  "Toes to bar": "Puntas a la barra",
  "Press francés": "Press francés con barra",
  "Fondos": "Fondos en paralelas",
  "Monster walk": "Caminata lateral con banda",
  "Hip thrust en máquina": "Empuje de cadera en máquina",
};

const norm = s => String(s || "").normalize("NFD").replace(/[̀-ͯ]/g, "").toLowerCase().replace(/[°º]/g, "").replace(/\s+/g, " ").trim();

const IDX = {};
Object.keys(V).forEach(k => { IDX[norm(k)] = V[k]; });
Object.keys(ALIAS).forEach(k => { const v = V[ALIAS[k]]; if(v) IDX[norm(k)] = v; });

// Video de la biblioteca para un nombre de ejercicio: { url, channel } o null.
export function libVideo(name){
  const v = IDX[norm(name)];
  return v ? { url: "https://www.youtube.com/shorts/" + v[0], channel: v[1] } : null;
}

// El video que ve el cliente: el link del coach si hay; si no, el de la biblioteca.
export function exVideo(ex){
  if(ex && ex.video && /^https:\/\//i.test(ex.video)) return { url: ex.video, channel: "" };
  return libVideo(ex && ex.name);
}
