// Biblioteca de videos de técnica: un Short de YouTube por ejercicio, siempre en español
// (los clientes están en Argentina), de entrenadores y kinesiólogos hispanohablantes.
// Solo se enlaza (se abre en YouTube): no se descarga ni se vuelve a subir nada, así el video
// sigue siendo de su autor, con su canal y su crédito. Si el coach pega su propio link en el
// ejercicio, manda el del coach.
// Cada lunes el workflow "Videos" revisa que sigan existiendo (scripts/verificar-videos.mjs).
//
// Clave: nombre del ejercicio como está en EX_DB (sin tildes ni mayúsculas, ver norm()).
// Valor: [id del Short, canal].

const V = {
  "Press de banca plano (barra)": ["8NF3wRkmGbw", "Emearenafit"],
  "Press de banca inclinado (barra)": ["5XRE9cnnfVw", "Emearenafit"],
  "Press de banca declinado": ["HVFEYGoBo1w", "Leo Romano preparador rugby"],
  "Press plano con mancuernas": ["O_NGJ2DcBAs", "Alex Valdez"],
  "Press inclinado con mancuernas": ["a64mtMHyPfY", "Dra. Isabel Junio"],
  "Press plano en Smith": ["ReuWQou1ZcM", "Coach Luis Solís"],
  "Press inclinado en Smith": ["MQWf9GnKHV0", "Coach Luis Solís"],
  "Aperturas con mancuernas": ["GpcnB88kYYw", "Salvador Gambín"],
  "Aperturas inclinadas": ["UmizgPQUSoY", "Javi NewBody"],
  "Aperturas en máquina": ["kGVhRoYlb50", "BenjaminTrainer"],
  "Cruce de poleas": ["5l8ba5QVdRA", "Martinhm"],
  "Vuelos en polea": ["lWRetnPV050", "Salud Íntegra"],
  "Fondos en paralelas": ["3QaC4rZKI8o", "Kevin Hernández NB"],
  "Flexiones de brazos": ["sz_z2TQ_sWQ", "Escuela de Suboficiales Sargento Cabral"],
  "Press de pecho en máquina": ["qbkrwo9fTiw", "Vitar Club"],
  "Peck deck": ["SgXn1Q81pHU", "Mauro Fialho"],
  "Cruce de poleas descendente": ["_QwO5I3dHU8", "Zonapablo"],
  "Press declinado con mancuernas": ["hyp_HRqi_Ig", "Coach Luis Solís"],
  "Aperturas en polea baja": ["0ouCLm08EXg", "Andres Vazquez Personal Trainer"],
  "Flexiones diamante": ["2CKtDrtzBZU", "Zenkai Kaizen Fitness"],
  "Press de pecho en máquina inclinado": ["ylPIQf5IBs4", "Anderson C. Ortega"],
  "Press militar con barra": ["-5ftONzAfIg", "Salud Íntegra"],
  "Press Arnold": ["oXovVgDq2Tk", "Sergio Orduz"],
  "Press de hombros con mancuernas": ["eHY09oHxzQg", "Bruno Requena"],
  "Press de hombros en Smith": ["0T7cGfsIHAs", "Deportika Online"],
  "Vuelos laterales con mancuernas": ["zEANAIh1l9g", "Karen Zárate"],
  "Vuelos laterales en polea": ["c5faaytfrWI", "Maru lekhal"],
  "Vuelos laterales en máquina": ["bZgXkYJFBOc", "Mauro Fialho"],
  "Vuelos posteriores": ["dnUpZK26C4A", "Manuel Escalera"],
  "Posterior en máquina": ["714DWH5o4Gg", "Pablo Sanromán"],
  "Posterior en polea": ["vO-cQxJjMDc", "Trainologym"],
  "Elevaciones frontales": ["jk7YrK79ciA", "Alberto Hiciano IFBB PRO"],
  "Jalón a la cara": ["KDMz_ZjG09g", "Salud Íntegra"],
  "Encogimientos de hombros": ["Zz1VR4ivSos", "Fit Generation"],
  "Vuelo lateral en polea (énfasis estiramiento)": ["nOZvT_QMUEk", "Paula Suárez"],
  "Remo al mentón": ["2T6OtbB0-94", "Laura Rozo"],
  "Press landmine": ["UKB4Ere3zVE", "Cris Provecho"],
  "Press militar sentado": ["5jZGLKrVUpA", "VekaHealthyLife"],
  "Rotación externa en polea": ["70XEY9gEYig", "Doc Fitness"],
  "Dominadas": ["rn_wjhrclGw", "Aaron Viramontes HARDCOACH"],
  "Dominadas neutras": ["eSHaWsrTg9Y", "CLAUDIA ARTEAGA FIT"],
  "Jalón al pecho": ["TIZbG7Tjbf8", "Javi NewBody"],
  "Jalón neutro": ["_MGvvfP3zzA", "Marcos Moreno"],
  "Jalón en V": ["CRSaYsLR2qk", "Luna Boccia Morello"],
  "Jalón en estocada": ["QKoZthHBZiM", "Diego Colungo"],
  "Jalón con brazos rectos en polea": ["PmIPUYatE8s", "Salud Íntegra"],
  "Remo con barra": ["m57r3hS1cdo", "HIIT FIT"],
  "Remo Pendlay": ["3h4tXbw--xY", "Enrique Alcobendas"],
  "Remo unilateral con mancuerna": ["DnQytXQMqcw", "Fit Generation"],
  "Remo en máquina": ["mNnr_j72_pE", "BenjaminTrainer"],
  "Remo en máquina unilateral": ["h06sk-R3i4Q", "Olimpia 2.0"],
  "Remo en polea baja": ["D_UXjlrZIBw", "Maru lekhal"],
  "Remo en barra T": ["ZhsM1kY7HEs", "Néstor Sánchez González"],
  "Jalón con brazos rectos y mancuerna": ["d6zLDfcxzdc", "ENFAF"],
  "Hiperextensiones lumbares": ["bLPebovecmg", "Zona del Entrenador"],
  "Jalón unilateral en estocada": ["QKoZthHBZiM", "Diego Colungo"],
  "Remo neutro abierto en polea baja": ["0UQyG5iiiv8", "Fit Fat Market"],
  "Remo en polea baja unilateral": ["LzyCWrZT4Bw", "Daniel Solá - Entrenador Online"],
  "Remo alto en polea": ["MiekeChX-nM", "Emearenafit"],
  "Pullover en polea": ["E7CiaycXvXU", "Javi NewBody"],
  "Pullover con mancuerna": ["d6zLDfcxzdc", "ENFAF"],
  "Remo con mancuerna en banco inclinado": ["S0PR4R1sWUU", "Zona del Entrenador"],
  "Remo invertido": ["NJWqM0gLLsk", "Ignacio Nocelli"],
  "Dominadas asistidas": ["ZobRtwGd1ZQ", "Karen Zárate"],
  "Remo Meadows": ["6QMwXNMIeR8", "Raúl te entrena"],
  "Rack pull": ["VHeI5S8DAWA", "madelman"],
  "Curl con barra": ["MqYBweUzDT4", "Gym Topz"],
  "Curl con barra Z": ["QYhE8tKXnlg", "Emilio Guadix I Entrenador online"],
  "Curl con mancuernas": ["pY1eUygY3rY", "Zona del Entrenador"],
  "Curl alternado": ["gSArg_hEHDw", "Willee Araujo Coach"],
  "Curl martillo": ["KsVklsSOuKo", "Laura Rozo"],
  "Curl predicador": ["uXaz4wPNaxs", "Zona del Entrenador"],
  "Curl en banco inclinado": ["r5kZ6XPAwZg", "Estutrainer"],
  "Curl en polea": ["_cgSSelhgF8", "Priscilla_bc"],
  "Curl en polea detrás del cuerpo": ["pTizWI1NcYo", "Trainologym"],
  "Curl concentrado": ["kcakHyAiyZo", "FRANK SERAPIÓN"],
  "Curl araña": ["1MbBr8xkQac", "Alberto Hiciano IFBB PRO"],
  "Curl bíceps en polea baja frontal": ["488Rrl5Cd4g", "Daniela Galvez Duarte"],
  "Curl Bayesian": ["pTizWI1NcYo", "Trainologym"],
  "Curl predicador en polea": ["5ClD053YXzU", "Vietcapite"],
  "Curl martillo en polea": ["-omdK30TOjk", "Mauro Fialho"],
  "Curl en máquina": ["C0xuU9_wlkg", "JMF-PersonalTrainer"],
  "Curl 21": ["X4dkDkHEyR4", "Memo Fitgame"],
  "Curl con barra supino en polea": ["cr46GuiqIdI", "Mikel Hernández Recio"],
  "Press francés con barra": ["gkQAHNoXYfc", "Alberto Hiciano IFBB PRO"],
  "Press francés con mancuernas": ["u8w3Us_FWb4", "Martinhm"],
  "Extensión en polea": ["oZv1_FDe7D8", "ERRE Academy"],
  "Extensión con soga": ["hVxONCYIxNI", "Zona del Entrenador"],
  "Patada de tríceps": ["35U1T7p8MME", "Sergio Orduz"],
  "Press cerrado": ["v8z-nqlNfaE", "La Ciencia del Chándal"],
  "Fondos entre bancos": ["ztyyhVRtits", "Yulmarfit"],
  "Extensión sobre la cabeza": ["tx-TgvQCJpQ", "Powerexplosive"],
  "Katana en polea": ["ImsJtwR1FjU", "Martinhm"],
  "Katana en Smith": ["Np-eDvgjnL8", "Mauro Fialho"],
  "Extensión de tríceps parado en polea": ["FELcywKlkqE", "Galvistrainer"],
  "Extensión de tríceps unilateral en polea": ["C2iK3jLskvQ", "Patxi"],
  "Fondos en máquina": ["v1rlc4jdwkQ", "Zayeg Camarillo Coach"],
  "Extensión de tríceps en máquina": ["6iKEO0xT5jc", "Zona del Entrenador"],
  "Press JM": ["SHnUz_PAblo", "Jorgemasterfit"],
  "Curl de muñeca": ["l-QVuxn9MMk", "Josue Ramírez Fernandez"],
  "Curl de muñeca invertido": ["TjmowP_tm1U", "JMF-PersonalTrainer"],
  "Curl invertido con barra": ["hplJJt9lQb8", "MATI FERNANDEZ COACH FITNESS"],
  "Caminata del granjero": ["6iawBmXovwE", "Marca Personal Fitness"],
  "Curl de antebrazo en polea": ["g99p8VK1LTQ", "Lic. Jorge Delgadillo"],
  "Curl de muñeca con mancuerna": ["l-QVuxn9MMk", "Josue Ramírez Fernandez"],
  "Sentadilla libre": ["uDE_cTKusnk", "Sonnos Más"],
  "Sentadilla frontal": ["SJ97z1-YVGs", "Dra. Isabel Junio"],
  "Sentadilla en Smith": ["rQw8GUzpj1I", "Betty Armas"],
  "Sentadilla hack": ["itmlCUc0P3k", "GOfit"],
  "Prensa 45": ["voXz7k7PXIA", "Zona del Entrenador"],
  "Prensa horizontal": ["cMK4Q-aQJxY", "Priscilla_bc"],
  "Extensión de cuádriceps": ["xj5u9RvlkmA", "BenjaminTrainer"],
  "Extensión de cuádriceps a una pierna": ["xj5u9RvlkmA", "BenjaminTrainer"],
  "Zancadas": ["lMRGw-5_R40", "MH Entrenamiento - Mr. Glúteo"],
  "Sentadilla búlgara": ["KFXGzysScis", "MH Entrenamiento - Mr. Glúteo"],
  "Sentadilla con mancuerna al pecho": ["UiaS3Mnc6Sk", "Priscilla_bc"],
  "Subida al cajón": ["9XWxpd_kVko", "Dra. Isabel Junio"],
  "Sentadilla sissy": ["qKjPofztR2M", "Sportfitness"],
  "Cuadricera": ["xj5u9RvlkmA", "BenjaminTrainer"],
  "Sentadilla goblet": ["PDfLkpT-KTk", "Soy Powerlifter"],
  "Sentadilla pendular": ["Fa_lANc9kKQ", "David Ritter"],
  "Zancadas caminando": ["fwtKO83nG0A", "karlos Doncel"],
  "Zancada inversa": ["d8C_b8DRYSo", "POWER HIIT TV (Entrena con Jesús y Ruth)"],
  "Sentadilla sumo": ["OrWRflQgWnQ", "POWER HIIT TV (Entrena con Jesús y Ruth)"],
  "Gemelos de pie": ["_R3TOH-vnF8", "Fit Generation"],
  "Gemelos sentado": ["PJz2IcRQm8s", "Nacho Alcorta"],
  "Gemelos en prensa": ["gDys0mRFvgQ", "Trainologym"],
  "Gemelos en Smith": ["ErgksW7SR48", "Ninolift"],
  "Gemelos burro": ["oXJhd6Wm-iM", "Karen Zárate"],
  "Gemelos a una pierna": ["MSc1vcb0gWw", "TRAINING X EL MUNDO"],
  "Gemelos en máquina": ["syUFp_Na9RE", "Mauro Fialho"],
  "Elevación de tibial": ["2uVVBuwoGHs", "KneesOverToesGuy en Español"],
  "Curl femoral acostado": ["6JQflLWhKfg", "Karen Zárate"],
  "Curl femoral sentado": ["POgzKaM92X4", "Vitar Club"],
  "Curl femoral de pie": ["RBhV8ow4FeQ", "Galvistrainer"],
  "Peso muerto rumano": ["UgqrPwoTick", "MH Entrenamiento - Mr. Glúteo"],
  "Peso muerto rumano con mancuernas": ["SAdzug-v7D0", "Priscilla_bc"],
  "Peso muerto piernas rígidas": ["A4abfqXNNFQ", "AngelFCoach"],
  "Peso muerto convencional": ["LQ-ZXbLeyBs", "Julien LEPRETRE"],
  "Buenos días": ["RGZd_udGVeE", "Olaya Baker"],
  "Curl nórdico": ["_Rpgnt55_-o", "Ninolift"],
  "Camilla de isquios": ["VPSKSNXkkdE", "Am Entrenamiento"],
  "Peso muerto rumano a una pierna": ["wy9-Dp5ZsOE", "Ninolift"],
  "Curl femoral con fitball": ["wNxHyR54WBk", "FyC-TRAINING"],
  "Empuje de cadera": ["B9Me4gKiU-g", "Sergio Orduz"],
  "Empuje de cadera en máquina": ["uqweOejr2NQ", "Vitar Club"],
  "Puente de glúteo": ["QIQtIs6yfXk", "sofitmami"],
  "Patada de glúteo en polea": ["Oy8eojLf2tc", "Galvistrainer"],
  "Patada de glúteo en máquina": ["X6cqiB6wFCA", "MH Entrenamiento - Mr. Glúteo"],
  "Abductores": ["0wZ_dRSbnsA", "MH Entrenamiento - Mr. Glúteo"],
  "Abducción en polea": ["e3NNZ1y_QgU", "MH Entrenamiento - Mr. Glúteo"],
  "Aductores": ["rWpICXoh1qo", "Ninolift"],
  "Peso muerto sumo": ["_FLblNZsoq4", "Ibrahim Nino"],
  "Aductores en máquina": ["THMerthY-uQ", "Christian Kosmos"],
  "Empuje de cadera a una pierna": ["a7co03aKSto", "Diana Ayala"],
  "Patada de glúteo en cuadrupedia": ["rIebT2hwDJ8", "Bio Full Fit"],
  "Caminata lateral con banda": ["ES_ZKBlslEc", "Johan Zambrano"],
  "Hiperextensión para glúteo": ["MaaEnOvdQhU", "Karen Zárate"],
  "Step-up para glúteo": ["93pIOsYMSDQ", "MH Entrenamiento - Mr. Glúteo"],
  "Encogimiento abdominal": ["HLAPlJhxqEE", "El Nivel Fit"],
  "Encogimiento declinado": ["aYGRgupuBdw", "MH Entrenamiento - Mr. Glúteo"],
  "Elevación de piernas": ["k4-dCtjUXkA", "Julio Cabrera Fit"],
  "Elevación de piernas colgado": ["1YOwAYQd6Wc", "Pablo Sanromán"],
  "Plancha": ["0qbDFF4IiXc", "GIMENOF"],
  "Rueda abdominal": ["fJ0ulh6Gfa8", "Pablo Sanromán"],
  "Encogimiento en polea": ["MBGe6ncD2KI", "MH Entrenamiento - Mr. Glúteo"],
  "Giro ruso": ["9brzc9B1ZIU", "Cuídate con ERGO"],
  "Escaladores": ["W5dmhWF6sqA", "edwin arce"],
  "Oblicuos": ["VlyHNMcNThI", "Deportika Online"],
  "Plancha lateral": ["I1rfrsHLXpc", "POWER HIIT TV (Entrena con Jesús y Ruth)"],
  "Encogimiento invertido": ["XcPb-4kFfSw", "Deportika Online"],
  "Bicicleta abdominal": ["2oAwnfi3Paw", "soyjosefitness"],
  "Puntas a la barra": ["455nHNPl1T0", "Aquila fitness news"],
  "Plancha hueca": ["n_UF8mvU1fM", "Ninolift"],
  "Bicho muerto": ["1I_e0t-nXzg", "entrenador de habitos"],
  "Leñador en polea": ["qmKUpSRijgc", "Estutrainer"],
  "Encogimiento en máquina": ["MBGe6ncD2KI", "MH Entrenamiento - Mr. Glúteo"],
  "Bandera": ["bLCUS2XVIhU", "Hybrid Calisthenics en Español"],
  "Abdominales en V": ["CW624NAM9Us", "David Sáez"],
  "Crunch en banco": ["z5lVHx8FqPU", "defelicefitness"],
  "Pallof press": ["S_5GSYfIrso", "Trainologym"],
  "Elevación de rodillas en paralelas": ["esIU5EGoTfw", "JMF-PersonalTrainer"],
};

// Otros nombres con los que aparece el mismo ejercicio.
const ALIAS = {
  "Prensa 45°": "Prensa 45",
  "Remo T": "Remo en barra T",
  "Elevaciones laterales": "Vuelos laterales con mancuernas",
  "Vuelos laterales sentado": "Vuelos laterales con mancuernas",
  "Jalón prono": "Jalón al pecho",
  "Sentadilla": "Sentadilla libre",
  "Press de banca": "Press de banca plano (barra)",
  "Hip thrust": "Empuje de cadera",
  "Face pull": "Jalón a la cara",
  "Dead bug": "Bicho muerto",
  "Paseo del granjero": "Caminata del granjero",
  "Plancha abdominal": "Plancha",
  "Plancha frontal": "Plancha",
  "Curl alternado con mancuernas": "Curl alternado",
  "Pullover": "Pullover en polea",
  "Remo gironda": "Remo en polea baja",
  "Polea al pecho": "Jalón al pecho",
  "Estocadas": "Zancadas",
  "Sillón de cuádriceps": "Extensión de cuádriceps",
  "Crunch abdominal": "Encogimiento abdominal",
  "Crunch en polea": "Encogimiento en polea",
  "Crunch invertido": "Encogimiento invertido",
  "Toes to bar": "Puntas a la barra",
  "Press francés": "Press francés con barra",
  "Fondos": "Fondos en paralelas",
  "Monster walk": "Caminata lateral con banda",
  "Hip thrust en máquina": "Empuje de cadera en máquina",
};

const norm = s => String(s || "").normalize("NFD").replace(/[̀-ͯ]/g, "").toLowerCase().replace(/[°º]/g, "").replace(/\s+/g, " ").trim();

const IDX = {};
Object.keys(V).forEach(k => { IDX[norm(k)] = V[k]; });
Object.keys(ALIAS).forEach(k => { const v = V[ALIAS[k]]; if(v) IDX[norm(k)] = v; });

// Video de la biblioteca para un nombre de ejercicio: { url, channel } o null.
export function libVideo(name){
  const v = IDX[norm(name)];
  return v ? { url: "https://www.youtube.com/shorts/" + v[0], channel: v[1] } : null;
}

// El video que ve el cliente: el link del coach si hay; si no, el de la biblioteca.
export function exVideo(ex){
  if(ex && ex.video && /^https:\/\//i.test(ex.video)) return { url: ex.video, channel: "" };
  return libVideo(ex && ex.name);
}
